plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = 'https://maven.minecraftforge.net/' }

}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.resources.srcDir 'src/generated/resources'

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/generated/resources"))
    }
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "com.github.glitchfiend:TerraBlender-fabric:${minecraft_version}-${terrablender_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

}

loom {
    def aw = project.file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            inherit client
            name "Data Generation"
            setConfigName('Fabric Datagen')
            ideConfigGenerated(true)

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/generated/resources")}"
            vmArg "-Dfabric-api.datagen.modid=${mod_namespace}"

            runDir 'runs/datagen'
        }
    }
}



processResources {
    def props = [
            "version": project.version,
            "mod_id": mod_id,
            "mod_name": mod_name,
            "mod_description": mod_description,
            "mod_authors": mod_authors,
            "loader_version": loader_version,
            "minecraft_version_range": minecraft_version_range,
            "minecraft_version": minecraft_version,
            "terrablender_version": terrablender_version
    ]
    inputs.properties(props)

    filesMatching("fabric.mod.json") {
        expand props
    }
}

java {

    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}


    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "file://${project.projectDir}/repo"
            }
        }
    }

